/*
*	Created:			04.06.10
*	Author:				009
*	Description:		Цвета.
*/

#if defined _colors_included
	#endinput
#endif

#define _colors_included
#pragma library colors

// --------------------------------------------------
// defines
// --------------------------------------------------
#define COLOR_BLACK 0x000000AA 		// black
#define COLOR_GREY 0xAFAFAFAA 		// grey
#define COLOR_GREEN 0x33AA33AA 		// green
#define COLOR_LIGHTGREEN 0x9ACD32AA //lightgreen
#define COLOR_RED 0xAA3333AA 		// red
#define COLOR_LIGHTRED 0xFF6347AA 	// lightred
#define COLOR_YELLOW 0xFFFF00AA 	// yellow
#define COLOR_WHITE 0xFFFFFFAA 		// white
#define COLOR_BLUE 0x33AAFFAA 		// blue
#define COLOR_LIGHTBLUE 0x33CCFFAA 	// LightBlue
#define COLOR_ORANGE 0xFF9900AA 	//orange
#define COLOR_PINK 0xFF66FFAA 		// pink
#define COLOR_PURPLE 0xC2A2DAAA 	//purple
#define COLOR_TURQ 0x00A3C0AA 		// turq